COUNTRY_AIRPORTS = {
    "pakistan": "ISB",
    "thailand": "BKK",
    "japan": "HND",
    "france": "CDG",
    "italy": "FCO",
    "germany": "FRA",
    "united kingdom": "LHR",
    "uk": "LHR",
    "usa": "JFK",
    "united states": "JFK",
    "canada": "YYZ",
    "australia": "SYD",
    "new zealand": "AKL",
    "malaysia": "KUL",
    "singapore": "SIN",
    "uae": "DXB",
    "united arab emirates": "DXB",
    "saudi arabia": "JED",
    "qatar": "DOH",
    "turkey": "IST",
    "south korea": "ICN",
    "china": "PEK",
    "india": "DEL",
    "indonesia": "DPS",
    "vietnam": "HAN",
    "sri lanka": "CMB",
    "nepal": "KTM",
    "maldives": "MLE",
    "egypt": "CAI",
    "south africa": "JNB",
    "brazil": "GRU",
    "mexico": "MEX",
}