"""add trip planning fields

Revision ID: f03e723a8148
Revises: 
Create Date: 2026-07-02 15:31:36.937156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f03e723a8148'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("trips", sa.Column("origin", sa.String(), nullable=True))
    op.add_column("trips", sa.Column("transport_mode", sa.String(), nullable=True))
    op.add_column("trips", sa.Column("trip_type", sa.String(), nullable=True))
    op.add_column("trips", sa.Column("hotel_preference", sa.String(), nullable=True))
    op.add_column("trips", sa.Column("pace", sa.String(), nullable=True))

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'pace')
    op.drop_column('trips', 'hotel_preference')
    op.drop_column('trips', 'trip_type')
    op.drop_column('trips', 'transport_mode')
    op.drop_column('trips', 'origin')
    # ### end Alembic commands ###
